### ISSUE TITLE
Always creates 2 bars (Windows msys2, CentOS 7.4)

### ISSUE THREAD

**Issue by JorySchossau** [euantorano/progress.nim#2]
I recreated the demo, but I always get 2 bars, perhaps related to the extra printing of a '%' symbol?

```
[================================================.....................] 69.00%%
[=====================================================================>] 100.00%
```

nim v 0.19.4 installed progress via nimble

**Comment by euantorano** [comment]
Interesting, I’ll have to test this out and see if I can recreate the problem. Thanks for the report!

**Comment by JorySchossau** [comment]
Some more information.
On windows:
run though cmd, all operates correctly (single bar, fits window width)
run through msys2 it fails to find the terminal width correctly and produces 2 bars.
Usually, running a failing CLI utility using winpty (`wintpy ./test.exe`) fixes these kinds of issues, but not here.

**Comment by JorySchossau** [comment]
I get the same symptom of 2 bars on native CentOS 7.4 if I try setting the total to 1000 then calling increment() 1000 times:

```
[=====...............................................................] 6.80%%
[====================================================================>] 100.00%
```

**Comment by euantorano** [comment]
Interesting! Thanks for the detailed information. I’ve only tested on Windows (PowerShell + CMD) and Mac personally, but I’ll have a try with some other platforms and see if I can track down the issue.

**Comment by euantorano** [comment]
Yeah, I can re-produce this on my Mac too, it's pretty odd what it does here though:

![progressnim](https://user-images.githubusercontent.com/748913/53596712-44644300-3b98-11e9-9a14-d740fb6d22a9.gif)

It seems that `isComplete()` is returning true prematurely, I need to work out why.
