### ISSUE TITLE
Sometimes i get newlines on every update

### ISSUE THREAD

**Issue by faulander** [euantorano/progress.nim#4]
![image](https://user-images.githubusercontent.com/38588197/79130347-1b583f00-7da7-11ea-91f7-5060bbb0564f.png)

Running on Windows 10, 64bit with Nim 1.2.0

Code: 
```
for dir in walkDirRec(sourceDir, yieldFilter={pcDir}): #traverse all dirs in source path
  var amountOfFilesInDir = countFiles(dir, @[".jpg", ".jpeg"])
  var bar = newProgressBar(amountOfFilesInDir)
  echo "Processing Directory ", dir, " with ", intToStr(amountOfFilesInDir), " files."
  bar.start()
  for file in walkDirRec(dir, yieldFilter={pcFile}): # traverse all files in dir
    deleted = delUnwantedFiles(file)
    if (find(toLower(file), ".jpg") > 0 or find(toLower(file), ".jpeg") > 0) and deleted == false:
      #var details = getFileDetails(file)
      var resultOfResize = resizeImage(file, 60)
      bar.increment()
  bar.finish()
```

**Comment by euantorano** [comment]
That’s odd, I’m not sure what would cause that, but will test it and see if I can find a reason.

**Comment by faulander** [comment]
I checked the source and couldn't find the source. It might be the flush command not correctly working on windows. i'll try and run it on a *nix shell and give you feedback.

**Comment by faulander** [comment]
I created a pull requests with a fix that works for me on windows AND Linux.

**Comment by euantorano** [comment]
Thanks, I'll test today to make sure it works for me, then merge and tag a new release.
